In [1]:
#import pandas as pd
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sqlalchemy import create_engine
#from pandas_profiling import ProfileReport


In [2]:
#files to load

hospital_profitability1 = "Resources/hospital-profitability-2009-2013.csv"
hospital_profitability2= "Resources/hospital-profitability-2009-2013-2.csv"

profit1= pd.read_csv(hospital_profitability1)
profit2=pd.read_csv(hospital_profitability2)

profit1.head()
#merge or join datasets? they look the exact same have same values and colum names
# Combine the data into a single dataset
#profitcombo = pd.merge(profit1, profit2, how="left", on=["Year"])
#profitcombo.head()


Empty DataFrame
Columns: [year, hospital_id, facility_number, facility_name, begin_date, end_date, county_name, control_type, income_statement_item, income_statement_amount, patient_adjusted_day]
Index: []

In [3]:
profit2.head()

Year  Facility Number     Facility Name  Begin Date    End Date  \
0  2009      106010735.0  ALAMEDA HOSPITAL  07/01/2008  06/30/2009   
1  2009      106010735.0  ALAMEDA HOSPITAL  07/01/2008  06/30/2009   
2  2009      106010735.0  ALAMEDA HOSPITAL  07/01/2008  06/30/2009   
3  2009      106010735.0  ALAMEDA HOSPITAL  07/01/2008  06/30/2009   
4  2009      106010735.0  ALAMEDA HOSPITAL  07/01/2008  06/30/2009   

  County Name Type of Control Income Statement Item  Income Statement Amount  \
0     Alameda        District             GR_PT_REV              282813469.0   
1     Alameda        District      DED_REV_PLUS_DSH              219753983.0   
2     Alameda        District           TOT_CAP_REV                      0.0   
3     Alameda        District      NET_REV_LESS_DSH               63059486.0   
4     Alameda        District            OTH_OP_REV                 192252.0   

   Amount per Adjusted Patient Day  
0                           5220.0  
1                           4056.0  
2                              0.0  
3                           1164.0  
4                              4.0

In [4]:
## 1. Identify if datasets are identical:
# resource: https://stackoverflow.com/questions/20225110/comparing-two-dataframes-and-getting-the-differences/52047609#52047609
#identify if the columns heading are equal
if profit1.columns.all() == profit2.columns.all():
    print('columns are same')
else:
    print('columns differ')
#Compare dfs: concat dfs and drop all duplicates to get the df of differences
df_diff = pd.concat([profit1,profit2]).drop_duplicates(keep=False)
print(f'number of different rows in dfs: {len(df_diff)}')
df_diff
# DatasestS are identical. Will work with profit1 df. Dropping Profit2 dataset

columns differ
number of different rows in dfs: 28626


year hospital_id facility_number facility_name begin_date end_date  \
0      NaN         NaN             NaN           NaN        NaN      NaN   
1      NaN         NaN             NaN           NaN        NaN      NaN   
2      NaN         NaN             NaN           NaN        NaN      NaN   
3      NaN         NaN             NaN           NaN        NaN      NaN   
4      NaN         NaN             NaN           NaN        NaN      NaN   
...    ...         ...             ...           ...        ...      ...   
28621  NaN         NaN             NaN           NaN        NaN      NaN   
28622  NaN         NaN             NaN           NaN        NaN      NaN   
28623  NaN         NaN             NaN           NaN        NaN      NaN   
28624  NaN         NaN             NaN           NaN        NaN      NaN   
28625  NaN         NaN             NaN           NaN        NaN      NaN   

      county_name control_type income_statement_item income_statement_amount  \
0             NaN          NaN                   NaN                     NaN   
1             NaN          NaN                   NaN                     NaN   
2             NaN          NaN                   NaN                     NaN   
3             NaN          NaN                   NaN                     NaN   
4             NaN          NaN                   NaN                     NaN   
...           ...          ...                   ...                     ...   
28621         NaN          NaN                   NaN                     NaN   
28622         NaN          NaN                   NaN                     NaN   
28623         NaN          NaN                   NaN                     NaN   
28624         NaN          NaN                   NaN                     NaN   
28625         NaN          NaN                   NaN                     NaN   

       ...    Year  Facility Number     Facility Name  Begin Date    End Date  \
0      ...  2009.0      106010735.0  ALAMEDA HOSPITAL  07/01/2008  06/30/2009   
1      ...  2009.0      106010735.0  ALAMEDA HOSPITAL  07/01/2008  06/30/2009   
2      ...  2009.0      106010735.0  ALAMEDA HOSPITAL  07/01/2008  06/30/2009   
3      ...  2009.0      106010735.0  ALAMEDA HOSPITAL  07/01/2008  06/30/2009   
4      ...  2009.0      106010735.0  ALAMEDA HOSPITAL  07/01/2008  06/30/2009   
...    ...     ...              ...               ...         ...         ...   
28621  ...  2013.0              NaN               NaN         NaN         NaN   
28622  ...  2013.0              NaN               NaN         NaN         NaN   
28623  ...  2013.0              NaN               NaN         NaN         NaN   
28624  ...  2013.0              NaN               NaN         NaN         NaN   
28625  ...  2013.0              NaN               NaN         NaN         NaN   

      County Name Type of Control Income Statement Item  \
0         Alameda        District             GR_PT_REV   
1         Alameda        District      DED_REV_PLUS_DSH   
2         Alameda        District           TOT_CAP_REV   
3         Alameda        District      NET_REV_LESS_DSH   
4         Alameda        District            OTH_OP_REV   
...           ...             ...                   ...   
28621   Statewide             NaN       NET_OP_LESS_DSH   
28622   Statewide             NaN             NONOP_REV   
28623   Statewide             NaN             NONOP_EXP   
28624   Statewide             NaN               INC_TAX   
28625   Statewide             NaN              EXT_ITEM   

      Income Statement Amount  Amount per Adjusted Patient Day  
0                2.828135e+08                           5220.0  
1                2.197540e+08                           4056.0  
2                0.000000e+00                              0.0  
3                6.305949e+07                           1164.0  
4                1.922520e+05                              4.0  
...                       ...                              .

In [5]:
## 2. assign value 0 if any duplicates 
print(f"Number if duplicated rows in df: {len(profit1[profit1.duplicated(keep='first') == True])}")

profit1[profit1.duplicated(keep='first') == True]

Number if duplicated rows in df: 0


Empty DataFrame
Columns: [year, hospital_id, facility_number, facility_name, begin_date, end_date, county_name, control_type, income_statement_item, income_statement_amount, patient_adjusted_day]
Index: []

In [6]:
profit1.describe()

year hospital_id facility_number facility_name begin_date end_date  \
count     0           0               0             0          0        0   
unique    0           0               0             0          0        0   
top     NaN         NaN             NaN           NaN        NaN      NaN   
freq    NaN         NaN             NaN           NaN        NaN      NaN   

       county_name control_type income_statement_item income_statement_amount  \
count            0            0                     0                       0   
unique           0            0                     0                       0   
top            NaN          NaN                   NaN                     NaN   
freq           NaN          NaN                   NaN                     NaN   

       patient_adjusted_day  
count                     0  
unique                    0  
top                     NaN  
freq                    NaN

In [7]:
print (profit1.columns.tolist())

['year', 'hospital_id', 'facility_number', 'facility_name', 'begin_date', 'end_date', 'county_name', 'control_type', 'income_statement_item', 'income_statement_amount', 'patient_adjusted_day']


In [8]:
#Columns foucus needed for project 
new_profit_df= profit1[["Year", "Facility Number","Income Statement Item", "Income Statement Amount"]]
new_profit_df.head()

KeyError: "None of [Index(['Year', 'Facility Number', 'Income Statement Item',\n       'Income Statement Amount'],\n      dtype='object')] are in the [columns]"

In [11]:
## Rename the column headers

In [12]:



new_profit_df = new_profit_df.rename(columns={"Year": "year",
                                                  "Facility Number":"hospital_id",
                                                  "Income Statement Item":"income_statement_item",
                                                  "Income Statement Amount": "income_statement_amount"})


new_profit_df.drop_duplicates(inplace=True)
#new_profit_df.set_index("hospital_id", inplace=True)

new_profit_df.head()

year  hospital_id income_statement_item  income_statement_amount
0  2009  106010735.0             GR_PT_REV              282813469.0
1  2009  106010735.0      DED_REV_PLUS_DSH              219753983.0
2  2009  106010735.0           TOT_CAP_REV                      0.0
3  2009  106010735.0      NET_REV_LESS_DSH               63059486.0
4  2009  106010735.0            OTH_OP_REV                 192252.0

In [13]:
#Drop na values from hospital id
new_profit_df.dropna(subset=["hospital_id"], inplace = True)

In [14]:
#set hospital id as int type 
new_profit_df["hospital_id"]=new_profit_df["hospital_id"].astype("int64")

In [15]:
new_profit_df.dtypes 

year                         int64
hospital_id                  int64
income_statement_item       object
income_statement_amount    float64
dtype: object

In [16]:
new_profit_df.fillna(0,inplace=True)

In [17]:
new_profit_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28561 entries, 0 to 28614
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   year                     28561 non-null  int64  
 1   hospital_id              28561 non-null  int64  
 2   income_statement_item    28561 non-null  object 
 3   income_statement_amount  28561 non-null  float64
dtypes: float64(1), int64(2), object(1)
memory usage: 1.1+ MB


In [18]:
new_profit_df.describe()

year   hospital_id  income_statement_amount
count  28561.000000  2.856100e+04             2.856100e+04
mean    2010.987711  1.062803e+08             1.179110e+08
std        1.412736  1.370604e+05             4.126567e+08
min     2009.000000  1.060107e+08            -5.188873e+08
25%     2010.000000  1.061903e+08             0.000000e+00
50%     2011.000000  1.063011e+08             3.814370e+05
75%     2012.000000  1.063714e+08             3.472442e+07
max     2013.000000  1.065810e+08             1.059060e+10

In [19]:
new_profit_df.shape

(28561, 4)

In [20]:
new_profit_df.count()


year                       28561
hospital_id                28561
income_statement_item      28561
income_statement_amount    28561
dtype: int64

In [21]:
new_profit_df=new_profit_df.sort_values('hospital_id')
new_profit_df ['hospital_id'].unique()

array([106010735, 106010739, 106010776, 106010782, 106010805, 106010846,
       106010856, 106010858, 106010887, 106010937, 106010967, 106010987,
       106013619, 106013687, 106014034, 106014050, 106014207, 106014226,
       106014233, 106034002, 106040802, 106040875, 106040937, 106040962,
       106044006, 106050932, 106060870, 106070904, 106070924, 106070934,
       106070988, 106070990, 106071018, 106074017, 106074039, 106074097,
       106084001, 106090793, 106090933, 106094002, 106100005, 106100697,
       106100717, 106100745, 106100797, 106100899, 106104023, 106104047,
       106104062, 106104089, 106105029, 106105051, 106110889, 106121002,
       106121031, 106121051, 106121080, 106124004, 106130699, 106130760,
       106141273, 106141338, 106150706, 106150722, 106150736, 106150737,
       106150761, 106150775, 106150782, 106150788, 106150808, 106154022,
       106154101, 106154147, 106154160, 106160702, 106160725, 106160787,
       106164029, 106171049, 106171395, 106184008, 

In [29]:
new_profit_df=new_profit_df.sort_values('income_statement_amount')
new_profit_df ['income_statement_amount'].unique()

array([-5.18887343e+08, -4.27179204e+08, -4.07346529e+08, ...,
        9.39854233e+09,  9.46484675e+09,  1.05905995e+10])

In [33]:
new_profit_df=new_profit_df.sort_values('income_statement_item')
new_profit_df ['income_statement_item'].unique()

array(['DED_REV_PLUS_DSH', 'EXT_ITEM', 'GR_PT_REV', 'INC_TAX',
       'NET_INC_LESS_DSH', 'NET_OP_LESS_DSH', 'NET_REV_LESS_DSH',
       'NONOP_EXP', 'NONOP_REV', 'OPERATING_MARGIN', 'OTH_OP_REV',
       'TOT_CAP_REV', 'TOT_OP_EXP'], dtype=object)

In [34]:
new_profit_df=new_profit_df.sort_values('year')
new_profit_df ['year'].unique()

array([2009, 2010, 2011, 2012, 2013])

In [35]:
#new_profit_df=new_profit_df.sort_values('facility_number')
#new_profit_df ['facility_number'].unique()[:50]

In [ ]:
## Connection to Database 

In [36]:
from config import password

In [45]:
engine = create_engine(f'postgresql://postgres:{password}@localhost:5432/ETL_db')


In [46]:
#Confirm tables
engine.table_names()

['profit']

In [50]:
new_profit_df.to_sql(name ='profit', con=engine, if_exists='replace', index=True)

In [52]:
pd.read_sql_query('select * from profit', con=engine).head()

index  year  hospital_id income_statement_item  income_statement_amount
0   3046  2009    106301297             NONOP_EXP                 897178.0
1    191  2009    106014050             NONOP_EXP                 111438.0
2   5623  2009    106554011             NONOP_EXP                3819761.0
3     21  2009    106010739             NONOP_EXP                4366068.0
4    704  2009    106121080           TOT_CAP_REV                      0.0